In [1]:
import pandas as pd
import numpy as np

In [3]:
terror = pd.read_csv("terror_data.csv")

In [4]:
terror.head()

,Unnamed: 0,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,31921,201601020043,2016,1,2,NaN,1,NaN,217,United States,...,NaN,"""Protesters occupy Oregon wildlife refuge as d...","""Oregon standoff: 4 holdouts all in FBI custod...","""Federal indictment says protesters in Oregon ...",START Primary Collection,0,0,0,0,NaN
1,32089,201601070024,2016,1,7,NaN,0,NaN,217,United States,...,NaN,"""Philly Officer Heads Home 2 Weeks After Ambus...","""Islamic State sympathiser shoots Philadelphia...","""Philly cop wounded in street ambush,"" USA Tod...",START Primary Collection,-9,-9,0,-9,NaN
2,32394,201601150040,2016,1,15,NaN,0,NaN,217,United States,...,NaN,"""Muslim Man Beaten in the Bronx by Ski-Masked ...","""Teens who assaulted Muslim man chanted 'ISIS,...","""Two teens arrested for allegedly attacking Br...",START Primary Collection,-9,-9,1,1,NaN
3,33450,201602110023,2016,2,11,NaN,0,NaN,217,United States,...,"The victims included Neil McKeein, William Fol...","""Columbus machete attack motive,"" CNN, Februar...","""Random act or Islamist terrorism? Questions l...","""Ohio Machete attacker Mohamed Barry was inves...",START Primary Collection,-9,-9,0,-9,NaN
4,33764,201602180063,2016,2,18,NaN,0,NaN,217,United States,...,There is doubt that this incident meets terror...,"""Judge: Nashville man not competent to stand t...","""Brown County man not mentally competent to st...",NaN,START Primary Collection,-9,-9,1,1,NaN

In [11]:
df = pd.read_csv("merged.csv")

In [47]:
df[df['DEP_DELAY']>200].shape

(2642, 30)